### ISSUE TITLE
Nova Installation Error

### ISSUE THREAD

**Issue by nonofficialcover** [DataSoft/Nova#2]
Hi! I'm trying to install Nova using both manual anfd automatic installation script. 
Unfortunately I'm getting what seems to be the same errors. I hope someone could help me out.
I've pasted excerpts of the installation errors below for reference. Thank you in advance!

---

npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/minimatch/node_modules/lru-cache/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
npm ERR! cwd /root/nova-build/Nova/Quasar
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm ERR! path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/minimatch/node_modules/lru-cache/.npmignore
npm ERR! fstream_path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/minimatch/node_modules/lru-cache/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack Writer._finish.er.fstream_finish_call (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! Error: ENOENT, chown '/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
npm ERR! cwd /root/nova-build/Nova/Quasar
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm ERR! path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream/.npmignore
npm ERR! fstream_path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack Writer._finish (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19)
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream'
File exists: /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream
Move it away, and try again.

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
npm ERR! cwd /root/nova-build/Nova/Quasar
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm ERR! path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream
npm ERR! fstream_path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/ps-tree/node_modules/event-stream/LICENCE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:45:53
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/minimatch/node_modules/sigmund/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
npm ERR! cwd /root/nova-build/Nova/Quasar
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm ERR! path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/minimatch/node_modules/sigmund/README.md
npm ERR! fstream_path /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/minimatch/node_modules/sigmund/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack Writer._finish.er.fstream_finish_call (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/mute-stream
npm http 304 https://registry.npmjs.org/pkginfo
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/forever/node_modules/utile/node_modules'
npm ERR! error rolling back  forever@0.14.1 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/forever/node_modules/utile/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/forever/node_modules/utile/node_modules' }
npm ERR! Error: No compatible version found: minimist@'^1.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.1.0","0.2.0","1.0.0","1.1.0","1.1.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:553:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:477:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
npm ERR! cwd /root/nova-build/Nova/Quasar
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/mute-stream
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/eyes
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/nova-build/Nova/Quasar/npm-debug.log
npm ERR! not ok code 0
Error occurred during build process; terminating script!
root@nov:~#

**Comment by awaldow** [comment]
Well, the first things I notice are both less than ideal: you're installing nova as root (needs to be installed under the 'nova' user) and your node/npm versions are highly out of date. What OS are you trying to install this on?

**Comment by nonofficialcover** [comment]
Hello! I'm using Ubuntu 12.04.4.
Thank you for pointing out the root installation.
What's weird though is I've tries installing this on quite a number of boxes as root and it's only til recently that I've encountered any problem. I'll try installing it as 'nova'.

**Comment by nonofficialcover** [comment]
I ran the installation using 'nova' user and it's a no joy. Still getting the same errors.
I also tried updating nodej and npm but to no avail....

**Comment by awaldow** [comment]
It looks like maybe the node install for getting the node_modules folder
failed midway, there are a lot of ENOENT's for files in node_modules
subdirectories. Try and uninstall node and npm and use the downloaded node
version in the Quasar directory to make/install from scratch. I don't know
what else the problem could be if the versions of node and npm are correct,
aside from a bad npm install that didn't get cleaned up.

Addison

**Comment by gsakel1** [comment]
I installed on Centos7 successfully, but I had a similar error. After the getDependencies.sh script runs, I had to update npm, but NOT node. To do this I ran:

npm install npm -g --ca=""

I added this line right before you change permissions on the .npm/ directory:
chown -R $NEW_PERM .npm/

Hopefully this helps!

**Comment by nonofficialcover** [comment]
Thank you! Following your advise, I was able to install the Nova. 
Quasar runs now and I can access the GUI. However, for some reason I can't run the haystack. 
I'm getting a "interface_new: intf_get" error

P.S. - I'm trying to follow this step >> I added this line right before you change permissions on the .npm/ directory: chown -R $NEW_PERM .npm/ >> but I can't seem to find the npm directory you mentioned.

**Comment by awaldow** [comment]
.npm would be in your home directory, or at least it should be. It'd be under the $HOME of the user it was installed under.

interface_new: intf_get means honeyd is having problems finding the interface that it's being told to use. Are your interfaces names eth0, eth1, etc.? Or something else? Can you try running the following command on the command line and show the output?

novacli start haystack debug

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:
-------------------------------------------------------------------------------
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack
-------------------------------------------------------------------------------

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:
-------------------------------------------------------------------------------
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack
-------------------------------------------------------------------------------

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:
-------------------------------------------------------------------------------
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack
-------------------------------------------------------------------------------

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:
-------------------------------------------------------------------------------
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack
-------------------------------------------------------------------------------

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:
-------------------------------------------------------------------------------
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack
-------------------------------------------------------------------------------

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:
-------------------------------------------------------------------------------
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack
-------------------------------------------------------------------------------

**Comment by nonofficialcover** [comment]
Hi! I'm using "eth0" as the interface name.  Below is the command output you asked for:

---

Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[1488]: started with -i undefined --disable-webserver -i lo -f /home/infosec/.config/nova/config/haystack_honeyd.config -p /usr/share/nova/sharedFiles/nmap-os-db -s /var/log/honeyd/honeydHaystackservice.log -t /var/log/honeyd/ipList -m /usr/share/nova/sharedFiles/nmap-mac-prefixes -d
honeyd[1488]: interface_new: intf_get
Failed to start Haystack

---

Thank you very much!

**Comment by nonofficialcover** [comment]
Hi Guys,

I still can't install Nova after so many attempts. 
Would appreciate if someone could help me out please.

My last attempt was a straight forward install from a fresh Ubuntu 12.04 and running:

> wget https://raw.github.com/DataSoft/Nova/master/debian/novaInstallHelper.sh
> sudo bash novaInstallHelper.sh

## Still getting the errors:

npm ERR! Error: No compatible version found: clone@'^1.0.2'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.1.16","0.1.17","0.1.18","0.2.0","0.1.19","1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:553:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:477:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
npm ERR!     at Object.oncomplete (fs.js:297:15)

## .......

Thank you very much.
