### ISSUE TITLE
Nova Install errors

### ISSUE THREAD

**Issue by deni37** [DataSoft/Nova#4]
Trying to install Nova/Honeyd on Ubuntu 14.04 but can not get it up and running. I have tried both the installer and build/install. When I build/install I get:

denid@OTA-Laptop:~/nova$ sudo ./configure
checking for iptables... iptables
checking for setcap... setcap
checking for sqlite3... sqlite3
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pcap_create in -lpcap... yes
checking for main in -lann... yes
checking for pthread_create in -lpthread... yes
checking for curl_easy_init in -lcurl... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for boostlib >= 1.42... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not find a version of the library!
If I run the getDependencies.sh file, I get the following errors:
Already found correct nodejs version. Skipping.
npm http GET https://registry.npmjs.org/forever
npm http 304 https://registry.npmjs.org/forever
npm http GET https://registry.npmjs.org/cliff
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/flatiron
npm http GET https://registry.npmjs.org/forever-monitor
npm http GET https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/nssocket
npm http GET https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/shush
npm http GET https://registry.npmjs.org/prettyjson
npm http GET https://registry.npmjs.org/timespan
npm http GET https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/cliff
npm http 304 https://registry.npmjs.org/flatiron
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/nssocket
npm http 304 https://registry.npmjs.org/nconf
npm http 304 https://registry.npmjs.org/forever-monitor
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/shush
npm http 304 https://registry.npmjs.org/prettyjson
npm http 304 https://registry.npmjs.org/utile
npm http 304 https://registry.npmjs.org/timespan
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/winston
npm ERR! Error: No compatible version found: clone@'^1.0.2'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.1.16","0.1.17","0.1.18","0.2.0","0.1.19","1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:553:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:477:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-51-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
npm ERR! cwd /home/denid/nova-build/Nova/Quasar
npm ERR! node -v v0.8.5
npm ERR! npm -v 1.1.46
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/denid/nova-build/Nova/Quasar/npm-debug.log
npm ERR! not ok code 0
--2015-11-12 15:11:57--  http://v8-juice.googlecode.com/files/libv8-convert-20120219.tar.gz
Resolving v8-juice.googlecode.com (v8-juice.googlecode.com)... 173.194.207.82, 2607:f8b0:400d:c04::52
Connecting to v8-juice.googlecode.com (v8-juice.googlecode.com)|173.194.207.82|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 677276 (661K) [application/x-gzip]
Saving to: ‘libv8-convert-20120219.tar.gz.1’

100%[===================================================================================================================================================>] 677,276      853KB/s   in 0.8s

2015-11-12 15:11:58 (853 KB/s) - ‘libv8-convert-20120219.tar.gz’ saved [677276/677276]

Not matter how I try to install, I always end up with: 
Starting quasar with the forever daemon
/usr/bin/quasar: line 22: forever: command not found

Any help or pointers would be appreciated.

**Comment by shinzou87** [comment]
Hey there, I got the same error as you from a fresh install.

Try updating npm by running: 
$ sudo npm install -g npm

Should be ok after this

**Comment by NymphHEX** [comment]
http://v8-juice.googlecode.com/files/libv8-convert-20120219.tar.gz

link is broken, that why it didn't work
